---
title: "pivot_lobsters.Rmd"
author: "Alex Walker"
date: "07/08/2020"
output: html_document
---

##This is for Dplyr setup.
#### attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages('skimr')
library(kableExtra) #install.packages("kableExtra", dependencies = TRUE) 

## Read in Data

lobsters <- read_xlsx(here("data/lobsters.xlsx"), skip=4)

##Skimr

#One can look at a summary of statistics using summary(); however, it doesn't give a lot of useful information for non-numerical data. We instead use skimr
#skim lets us look more at each variable. We can look at our variables and see that there are 5 unique sites (in the n_unique output). Also, I particularly like looking at missing data. There are 6 missing values in the size_mm variable.

skimr::skim(lobsters)

## Group_by() %>% summarize()
#In R you can create pivot tables by using the above formula. This gives you the functionality of pivot tables in R. Note: The %>% operator is very important. It allows one to combine steps of data cleaning
#data %>% group_by(X) %>% summarize (Y = Z)

lobsters %>%
  group_by(year) %>%
  summarize(count_by_year = n())
  
##What if we want to group by more than one variable? This time let's group by site and year, not just year.

lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear = n())
  
##What is we wanted to summarize multiple varaibles? Say we wanted to calculate the mean and std? Using mean() and sd() we can do that. As well, using the na.rm = TRUE statement allows us to exclude NA data.

lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm=TRUE), 
            sd_size_mm = sd(size_mm, na.rm=TRUE))

## Now we want to save this summary information should we want to recall it later.

siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm=TRUE), 
            sd_size_mm = sd(size_mm, na.rm=TRUE))

siteyear_summary %>%
  kable()

siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm=TRUE), 
            sd_size_mm = sd(size_mm, na.rm=TRUE),
            median_size_mm = median(size_mm, na.rm = TRUE))

## a ggplot option:
ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +  geom_line() 

##To save this use
ggsave(here("figures", "lobsters-line.png"))

## What if we used the wrong data and we needed to use the other "Lobsters" data?
# read in data

lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip =4)

siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear =  n(), 
            mean_size_mm = mean(size_mm, na.rm = TRUE), 
            sd_size_mm = sd(size_mm, na.rm = TRUE), 
            median_size_mm = median(size_mm, na.rm = TRUE), )
            
siteyear_summary
            
ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +
  geom_line()
            
ggplot(siteyear_summary, aes(x = year, y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)
            
ggsave(here("figures", "lobsters-col.png"))

##dplyr::count()
#IF you want to only summarize by the count, you can use a function called count(). It will group_by the selected varaible.

lobsters %>%
  count(site, year)
  
#This is the same as:
lobsters %>%
  group_by(site, year) %>% 
  summarize(n = n()) %>%
  ungroup()
  
##Mutate()
#You can begin to operate on the data in columns by using the mutate() function from dplyr. 
lobsters %>%
  mutate(size_m = size_mm/1000)
#this would allow us to create a new column in which the size of the lobsters is now in meters.
#if we wanted to add a column that had the same value repeated we can pass it through

lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000, 
         millenia = 2000,
         observer = "Alex")
         
lobsters_detailed

##Select()
#This part ends with the select() function. This allows us to select only the data that we want to use.

lobsters_detailed %>%
  select(date,site, size_m)



         
         