---
title: "Creating graphs in R with `ggplot2`"
author: "Alex Walker"
date: "05/08/2020"
output: html_document
---

# Plots with ggplot2

library(tidyverse)
library(readxl)
library(here)

ca_np <- read_csv(here("data", "ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))

## To create a bare-bones ggplot graph, we need to tell R three basic things:
# We’re using ggplot2::ggplot()
# Data we’re using & variables we’re plotting (i.e., what is x and/or y?)
# What type of graph we’re making (the type of geom)

ggplot(data = df_name, aes(x = x_var_name, y = y_var_name)) +
  geom_type()
  
ggplot(data = ci_np, aes(x = year, y= visitors))+ geom_line()

#you can store the first line as an object. Call it gg_base
#After storing as object, you can change to scatterplot by gg_base+geom_point()

gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))

##We can change the aesthetics of elements in a ggplot graph by adding arguments within the layer where that element is created.
#Some common arguments we’ll use first are:
#color = or colour =: update point or line colors
#fill =: update fill color for objects with areas
#linetype =: update the line type (dashed, long dash, etc.)
#pch =: update the point style
#size =: update the element size (e.g. of points or line thickness)
#alpha =: update element opacity (1 = opaque, 0 = transparent)

gg_base+geom_line(color = "purple", linetype = "dashed")
gg_base+geom_point(color = "purple", pch = 17, size = 4, alpha = 0.5)
gg_base+geom_line(color = "cyan",size = 3, alpha = 0.8)

##When we want to customize a graph element based on a variable’s characteristic or value, add the argument within aes() in the appropriate geom_*() layer

gg_base+geom_point(aes(size = visitors, color = visitors), alpha = 0.5)

gg_base+geom_col(aes(fill = visitors))

##every element of a ggplot graph is manually customizable, there are also built-in themes (theme_*()) that you can add to your ggplot code to make some major headway before making smaller tweaks manually.

gg_base+geom_point(aes(size = visitors,color = visitors),alpha = 0.5) + theme_light()

gg_base + geom_line(linetype = "dotted") +theme_bw() +labs(
x = "Year",
y = "Annual park visitors",
title = "Channel Islands NP Visitation", 
subtitle = "(1963 - 2016)")

##As long as the geoms are compatible, we can layer them on top of one another to further customize a graph.

gg_base +
  geom_line(color = "purple") +
  geom_point(color = "orange",
             aes(size = year),
             alpha = 0.5)

##By using the group =() function we can produce multiple lines based on the grouping. Up to this point we have only been using the CI park data, but now we're going to graph all the parks in CA.      

ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) +  geom_line()

## You can add features to the multi series graph by altering the geom_line function.This removes the need to include the grouping in the ggplot layer

ggplot(data = ca_np, aes(x = year, y = visitors)) +  geom_line(aes(color = park_name))

gg_np <- ggplot(data = ca_np, aes(x = year, y =visitors, group = park_name))

## Using the facet_wrap() function we can split each group into their own plotting panels, where each panel contains it's own subset of data. 

gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)

## To export or save a graph we can use the ggsave function. ggsave() exports the most recently run ggplot graph by defualt. Some of the arugements to be used are:   
#width =: set exported image width (default inches)
#height =: set exported image height (default height)
#dpi =: set dpi (dots per inch)

ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)  

##Pivot Tables with dplyr